export const LOCAL_STORAGE_KEYS = {
  CASHU_P2PKKEYS: "cashu.P2PKKeys",
  CASHU_ACTIVEMINTURL: "cashu.activeMintUrl",
  CASHU_ACTIVEUNIT: "cashu.activeUnit",
  CASHU_BUCKETRULES: "cashu.bucketRules",
  CASHU_BUCKETS: "cashu.buckets",
  CASHU_DEXIE_MIGRATED: "cashu.dexie.migrated",
  CASHU_DMCHATS: "cashu.dmChats",
  CASHU_DMCHATS_UNREAD: "cashu.dmChats.unread",
  CASHU_DONATIONPRESETS: "cashu.donationPresets",
  CASHU_HISTORYTOKENS: "cashu.historyTokens",
  CASHU_INVOICEHISTORY: "cashu.invoiceHistory",
  CASHU_KEYSETCOUNTERS: "cashu.keysetCounters",
  CASHU_LASTLOCALSTORAGECLEANUP: "cashu.lastLocalStorageCleanUp",
  CASHU_LOCKEDTOKENS: "cashu.lockedTokens",
  CASHU_MESSENGER_CONVERSATIONS: "cashu.messenger.conversations",
  CASHU_MESSENGER_DRAWEROPEN: "cashu.messenger.drawerOpen",
  CASHU_MESSENGER_EVENTLOG: "cashu.messenger.eventLog",
  CASHU_MESSENGER_PINNED: "cashu.messenger.pinned",
  CASHU_MESSENGER_UNREAD: "cashu.messenger.unread",
  CASHU_MIGRATIONS_VERSION: "cashu.migrations.version",
  CASHU_MINTS: "cashu.mints",
  CASHU_MNEMONIC: "cashu.mnemonic",
  CASHU_NDK_LASTEVENTTIMESTAMP: "cashu.ndk.lastEventTimestamp",
  CASHU_NDK_MINTRECOMMENDATIONS: "cashu.ndk.mintRecommendations",
  CASHU_NDK_NIP17EVENTIDSWEHAVESEEN: "cashu.ndk.nip17EventIdsWeHaveSeen",
  CASHU_NDK_NIP46TOKEN: "cashu.ndk.nip46Token",
  CASHU_NDK_PRIVATEKEYSIGNERPRIVATEKEY: "cashu.ndk.privateKeySignerPrivateKey",
  CASHU_NDK_PUBKEY: "cashu.ndk.pubkey",
  CASHU_NDK_SEEDSIGNERPRIVATEKEY: "cashu.ndk.seedSignerPrivateKey",
  CASHU_NDK_SEEDSIGNERPUBLICKEY: "cashu.ndk.seedSignerPublicKey",
  CASHU_NDK_SIGNERTYPE: "cashu.ndk.signerType",
  CASHU_NPC_ADDRESS: "cashu.npc.address",
  CASHU_NPC_AUTOMATICCLAIM: "cashu.npc.automaticClaim",
  CASHU_NPC_BASEURL: "cashu.npc.baseURL",
  CASHU_NPC_CONNECTIONS: "cashu.npc.connections",
  CASHU_NPC_DOMAIN: "cashu.npc.domain",
  CASHU_NPC_ENABLED: "cashu.npc.enabled",
  CASHU_NUTZAP_SENDQUEUE: "cashu.nutzap.sendQueue",
  CASHU_NWC_CONNECTIONS: "cashu.nwc.connections",
  CASHU_NWC_ENABLED: "cashu.nwc.enabled",
  CASHU_NWC_RELAYS: "cashu.nwc.relays",
  CASHU_NWC_SEENCOMMANDSUNTIL: "cashu.nwc.seenCommandsUntil",
  CASHU_OLDMNEMONICCOUNTERS: "cashu.oldMnemonicCounters",
  CASHU_P2PK_SHOWP2PKBUTTONINDRAWER: "cashu.p2pk.showP2PkButtonInDrawer",
  CASHU_PR_ENABLE: "cashu.pr.enable",
  CASHU_PR_RECEIVE: "cashu.pr.receive",
  CASHU_PRICE_BITCOINPRICE: "cashu.price.bitcoinPrice",
  CASHU_PRICE_BITCOINPRICELASTUPDATED: "cashu.price.bitcoinPriceLastUpdated",
  CASHU_RESTORE_MNEMONICTORESTORE: "cashu.restore.mnemonicToRestore",
  CASHU_RESTORE_SHOWRESTOREDIALOG: "cashu.restore.showRestoreDialog",
  CASHU_SETTINGS_AUDITORAPIURL: "cashu.settings.auditorApiUrl",
  CASHU_SETTINGS_AUDITORENABLED: "cashu.settings.auditorEnabled",
  CASHU_SETTINGS_AUDITORURL: "cashu.settings.auditorUrl",
  CASHU_SETTINGS_AUTOPASTEECASHRECEIVE: "cashu.settings.autoPasteEcashReceive",
  CASHU_SETTINGS_AUTOREDEEMLOCKEDTOKENS:
    "cashu.settings.autoRedeemLockedTokens",
  CASHU_SETTINGS_CHECKINCOMINGINVOICES: "cashu.settings.checkIncomingInvoices",
  CASHU_SETTINGS_CHECKINVOICESONSTARTUP:
    "cashu.settings.checkInvoicesOnStartup",
  CASHU_SETTINGS_CHECKSENTTOKENS: "cashu.settings.checkSentTokens",
  CASHU_SETTINGS_DEFAULTNOSTRRELAYS: "cashu.settings.defaultNostrRelays",
  CASHU_SETTINGS_ENABLERECEIVESWAPS: "cashu.settings.enableReceiveSwaps",
  CASHU_SETTINGS_GETBITCOINPRICE: "cashu.settings.getBitcoinPrice",
  CASHU_SETTINGS_INCLUDEFEESINSENDAMOUNT:
    "cashu.settings.includeFeesInSendAmount",
  CASHU_SETTINGS_NFCENCODING: "cashu.settings.nfcEncoding",
  CASHU_SETTINGS_PERIODICALLYCHECKINCOMINGINVOICES:
    "cashu.settings.periodicallyCheckIncomingInvoices",
  CASHU_SETTINGS_SEARCHBACKENDURL: "cashu.settings.searchBackendUrl",
  CASHU_SETTINGS_TIERSINDEXERURL: "cashu.settings.tiersIndexerUrl",
  CASHU_SETTINGS_USENUMERICKEYBOARD: "cashu.settings.useNumericKeyboard",
  CASHU_SETTINGS_USEWEBSOCKETS: "cashu.settings.useWebsockets",
  CASHU_UI_EXPANDHISTORY: "cashu.ui.expandHistory",
  CASHU_UI_EXPANDP2PKKEYS: "cashu.ui.expandP2PKKeys",
  CASHU_UI_EXPANDPROFILEDETAILS: "cashu.ui.expandProfileDetails",
  CASHU_UI_EXPANDTIERLIST: "cashu.ui.expandTierList",
  CASHU_UI_HIDEBALANCE: "cashu.ui.hideBalance",
  CASHU_UI_LASTBALANCECACHED: "cashu.ui.lastBalanceCached",
  CASHU_UI_SHOWDEBUGCONSOLE: "cashu.ui.showDebugConsole",
  CASHU_UI_SHOWNFCBUTTONINDRAWER: "cashu.ui.showNfcButtonInDrawer",
  CASHU_UI_TAB: "cashu.ui.tab",
  CASHU_WELCOME_CURRENTSLIDE: "cashu.welcome.currentSlide",
  CASHU_WELCOME_SEEDPHRASEVALIDATED: "cashu.welcome.seedPhraseValidated",
  CASHU_WELCOME_SHOWWELCOME: "cashu.welcome.showWelcome",
  CASHU_WELCOME_TERMSACCEPTED: "cashu.welcome.termsAccepted",
  CASHU_WORKER_INVOICES_LASTPENDINGINVOICECHECK:
    "cashu.worker.invoices.lastPendingInvoiceCheck",
  CASHU_WORKER_INVOICES_QUOTESQUEUE: "cashu.worker.invoices.quotesQueue",
  CREATORHUB_LOGGEDINNPUB: "creatorHub.loggedInNpub",
  CREATORHUB_TIERORDER: "creatorHub.tierOrder",
  CREATORHUB_TIERS: "creatorHub.tiers",
  CREATORPROFILE_ABOUT: "creatorProfile.about",
  CREATORPROFILE_DISPLAY_NAME: "creatorProfile.display_name",
  CREATORPROFILE_MINTS: "creatorProfile.mints",
  CREATORPROFILE_PICTURE: "creatorProfile.picture",
  CREATORPROFILE_PUBKEY: "creatorProfile.pubkey",
  CREATORPROFILE_RELAYS: "creatorProfile.relays",
} as const;
