<template>
  <q-page :class="[$q.dark.isActive ? 'bg-dark text-white' : 'bg-white text-dark', 'q-pa-md']">
    <div class="text-h5 q-mb-md">{{ $t("AboutPage.title") }}</div>
    <p>Fundstr is a <strong>privacy-first Bitcoin wallet, social chat and creator-monetisation hub</strong> built on the open-source Cashu ecash protocol and the decentralised Nostr network. Everything you see in the sidebar is a doorway to a feature that either <strong>helps creators earn</strong> or <strong>lets fans support &amp; interact</strong> — all with instant, low-fee Bitcoin-denominated e-cash.</p>
    <p>Below you’ll find a <strong>page-by-page guide</strong> written in two parallel voices:</p>
    <ul>
      <li><strong>“Creator view”</strong> – what each screen means when you make money on Fundstr.</li>
      <li><strong>“Fan view”</strong> – what the same screen offers if you’re here to follow, tip and chat.</li>
    </ul>
    <div class="video-placeholder q-my-xl flex flex-center">
      {{ $t("AboutPage.video_placeholder") }}
    </div>
    <hr />
    <h3>1 How Fundstr works in one minute</h3>
    <ol>
      <li><strong>Load sats</strong> into Fundstr by paying a Lightning invoice generated by your chosen <strong>mint</strong>.</li>
      <li>The mint returns <em>blind-signed Cashu tokens</em> → you now hold unlinkable e-cash.</li>
      <li>Send those tokens to friends or creators by
        <ul>
          <li>pasting / scanning a QR, <strong>or</strong></li>
          <li>dropping them straight into a Nostr chat / zap event (the app handles security with <strong>P2PK locks</strong>).</li>
        </ul>
      </li>
      <li>Recipients redeem the tokens at the mint; nobody can trace sender ⇄ receiver.</li>
      <li>Creators optionally time-lock receipts for subscription models; fans keep proof-of-payment in their wallet.</li>
    </ol>
    <p>That’s the whole loop: <strong>Bitcoin in → private e-cash out → social payments everywhere</strong>.</p>
    <hr />
    <h2>2 Navigation map — every page explained</h2>
    <table>
      <thead>
        <tr>
          <th>🧭 Menu item</th>
          <th>Fan / Subscriber perspective</th>
          <th>Creator perspective</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>Settings</strong><br><span style="font-size:0.85em;">Wallet configuration</span></td>
          <td><em>Add / switch mints</em>, choose display unit, set language &amp; theme, import or back-up your 12-word seed, manage Nostr keys &amp; relays.</td>
          <td>Same, plus <strong>Publishing settings</strong>: toggle automatic NIP-61 profile updates and set a default “Earnings” bucket.</td>
        </tr>
        <tr>
          <td><strong>Find Creators</strong><br><span style="font-size:0.85em;">Discover creators</span></td>
          <td>Search or browse Nostr-indexed profiles. View tier prices, previews and public posts. Hit <strong>Subscribe</strong> or <strong>Zap</strong> with a single tap.</td>
          <td>Your public storefront as seen by visitors. Great for a quick audit of how your profile appears worldwide.</td>
        </tr>
        <tr>
          <td><strong>Creator Hub</strong><br><span style="font-size:0.85em;">Manage your tiers</span></td>
          <td>— <em>(hidden unless you toggle “Creator Mode”)</em></td>
          <td>Define or edit tiers (price, duration, perks), upload cover art, publish pay-walled posts, check revenue analytics and subscriber list.</td>
        </tr>
        <tr>
          <td><strong>My Profile</strong><br><span style="font-size:0.85em;">View your profile</span></td>
          <td>Show off your avatar, npub link and optional NIP-05. Personal stats: total zaps sent &amp; received, bucket balances.</td>
          <td>Same card plus <strong>Edit</strong>. Update bio, tags and the secondary P2PK key used by fans to send you locked tokens.</td>
        </tr>
        <tr>
          <td><strong>Buckets</strong><br><span style="font-size:0.85em;">Manage buckets</span></td>
          <td>Drag-and-drop jars for budgeting (“Groceries”, “Fun money”, “Subs”). Move sats with zero fees.</td>
          <td>Create an “Income” bucket that auto-receives new tips; split out taxes or savings instantly.</td>
        </tr>
        <tr>
          <td><strong>Subscriptions</strong><br><span style="font-size:0.85em;">Overview of your subscriptions</span></td>
          <td>See every active plan: tier name, next renewal, cumulative sats spent. Cancel or renew with one click.</td>
          <td>Quick list of paying supporters, tier breakdown, churn alerts and pending renewals.</td>
        </tr>
        <tr>
          <td><strong>Chats</strong></td>
          <td>End-to-end encrypted DMs (Nostr kind 4). Attach images or Cashu tokens. <strong>Green flash</strong> means a payment is embedded and auto-redeemed on receipt.</td>
          <td>Same powerful chat plus a <strong>broadcast</strong> toggle to message all subs in a tier at once (e.g. exclusive coupon codes).</td>
        </tr>
        <tr>
          <td><strong>Terms</strong></td>
          <td>Human-readable, plain-English licence &amp; disclaimers.</td>
          <td>Identical — clarifies you keep full custody of funds until you redeem at a mint.</td>
        </tr>
        <tr>
          <td><strong>About</strong> <em>(this page!)</em></td>
          <td>Learn everything in one scroll.</td>
          <td>Ditto; includes creator-specific FAQs below.</td>
        </tr>
        <tr>
          <td><strong>External links</strong></td>
          <td>Cashu.space docs, GitHub, Twitter, Telegram, Donate.</td>
          <td>Identical — share with collaborators or fans.</td>
        </tr>
      </tbody>
    </table>
    <hr />
    <h2>3 Feature deep-dive</h2>
    <h3>3.1 Wallet &amp; Buckets</h3>
    <ul>
      <li><strong>Fans</strong> keep spending and savings separate; rainbow-coloured progress rings show how close you are to a goal.</li>
      <li><strong>Creators</strong> set “Income”, “Escrow” (timelocked tokens) and “Operating costs” buckets to keep business clean.</li>
      <li><strong>Good to know:</strong> Moving sats <strong>never</strong> touches the blockchain; it’s just local bookkeeping.</li>
    </ul>
    <h3>3.2 Chats &amp; Nutzaps</h3>
    <ul>
      <li><strong>Fans</strong> – tap ➕ in a DM to send 10 sats with your message. Fundstr auto-wraps them in a P2PK lock so nobody but your friend can steal them.</li>
      <li><strong>Creators</strong> – receive tips right in the conversation; Fundstr pops a <em>“Thanks for the zap!”</em> ribbon and files the sats in your chosen bucket.</li>
    </ul>
    <h3>3.3 Subscriptions</h3>
    <ul>
      <li>Powered by <strong>timelocked tokens</strong>: when a fan subscribes, the app locks the payment so <strong>only you</strong> can redeem after the agreed period.</li>
      <li>Renewal reminders fire 48 h before expiry; one-tap to extend.</li>
      <li>Creators can set <strong>trial tiers</strong> (zero sats, 7 days) to funnel new users.</li>
    </ul>
    <h3>3.4 Mint audit tools</h3>
    <ul>
      <li>See circulating supply, key-rotation dates and swap histogram. If a mint behaves oddly Fundstr shows a red ⚠️ banner.</li>
      <li>Creators can whitelist mints they accept to avoid bad actors; fans get a prompt if they try to pay you from an untrusted source.</li>
    </ul>
    <h3>3.5 Nostr Wallet Connect (NWC)</h3>
    <ul>
      <li>Fans scan a pairing QR on any website → Fundstr handles future payments without copy-pasting invoices.</li>
      <li>Creators embed an NWC link on their blog; when a reader hits <em>Pay with Fundstr</em>, your wallet requests confirmation and settles instantly.</li>
    </ul>
    <hr />
    <h2>4 Creator &amp; Fan workflows</h2>
    <div style="display:grid;grid-template-columns:50% 50%;gap:1rem;">
      <h3>Fans — first 5 minutes</h3>
      <ol>
        <li>Install Fundstr PWA.</li>
        <li>Add a mint → fund 10 000 sats.</li>
        <li>Join a friend’s chat → send 500 sats.</li>
        <li>Browse <strong>Find Creators</strong> → subscribe to a 100 sat/month news tier.</li>
        <li>Balance auto-splits: <em>Fun money</em> 9 400 sats, <em>Subs</em> 100 sats, <em>Spent</em> 500 sats.</li>
      </ol>
      <h3>Creators — first 15 minutes</h3>
      <ol>
        <li>Toggle <strong>Creator Mode</strong> in Settings.</li>
        <li>Open <strong>Creator Hub</strong> → create a “Supporter” tier (1 000 sats / month).</li>
        <li>Publish NIP-61 profile with one click.</li>
        <li>Share your Fundstr link on Nostr.</li>
        <li>Watch first nutzap roll in, auto-redeem to “Income” bucket; thank supporter in chat.</li>
      </ol>
    </div>
    <hr />
    <h2>5 Frequently asked (split view)</h2>
    <details><summary>What if a fan stops paying?</summary><br>
    <b>Creator view »</b> Their timelocked token never unlocks for you, so there’s nothing to redeem. Fundstr flags the user as “Expired” and hides future paid posts.<br><br>
    <b>Fan view »</b> You simply don’t renew. No recurring pull, no surprise charges.
    </details>
    <details><summary>Can I withdraw to a normal Lightning wallet?</summary><br>
    Yes. Go to <em>Wallet → Send → Lightning Invoice</em>, paste the invoice from any external wallet; Fundstr melts the tokens at the mint and pays it.
    </details>
    <details><summary>How private is this really?</summary><br>
    • Mints see <i>withdraw</i>/<i>redeem</i> events but cannot correlate them.<br>
    • Nostr chats are E2E encrypted; Nutzaps use P2PK so only the intended receiver can claim the tokens.<br>
    • Choose different mints or buckets to compartmentalise further.
    </details>
    <details><summary>Fees?</summary><br>
    User-to-user transfers cost 0 sats.<br>
    Mints optionally charge a small Lightning routing fee on melts/withdraws; Fundstr displays it before you commit.
    </details>
    <hr />
    <h2>6 Stay safe &amp; thrive</h2>
    <ul>
      <li><strong>Back-up</strong> your 12-word seed and Nostr private key offline.</li>
      <li>Diversify across multiple mints for larger balances.</li>
      <li>Keep Fundstr updated — service-worker auto-updates bring the latest protocol fixes.</li>
      <li>Join the community:
        <ul>
          <li>Nostr hashtag <strong>#fundstr</strong> for tips &amp; support</li>
          <li>Telegram <strong>@FundstrWallet</strong></li>
          <li>GitHub issues for feature requests</li>
        </ul>
      </li>
    </ul>
    <hr />
    <blockquote>
      Fundstr is powered by open-source code and an open community. Whether you’re a <strong>storyteller earning sats</strong> or a <strong>fan supporting work you love</strong>, we hope this guide helps you navigate every page with confidence — and makes your next payment feel as effortless as a like, comment, or retweet.
    </blockquote>
  </q-page>
</template>

<script setup></script>

<style scoped>
.video-placeholder {
  height: 200px;
  border: 1px dashed #ccc;
  border-radius: 8px;
  color: #ccc;
  width: 100%;
}
</style>
