name: Test
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Use the skip config we added earlier so the job passes
      - run: pnpm dlx vitest@1.6.0 run -c vitest.skip.mts
